name: "Upload release to ShotGrid"
description: "Upload zipped release to ShotGrid"
runs:
  using: "composite"
  steps:
    - name: "Pip install Shotgun API"
      run: "python -m pip install git+git://github.com/shotgunsoftware/python-api.git"
      shell: bash
    - name: "ZIP Repository"
      run: |
        import os
        import shutil
        repo_path = os.environ["GITHUB_WORKSPACE"]
        output_path = os.path.join(
            os.environ["HOME"],
            f"{os.environ["REPO_NAME"]}-{os.environ["RELEASE_TAG"]}",
        )

        shutil.make_archive(output_path, "zip", repo_path)

      shell: python
    - name: "Upload to SG"
      run: |
        import os
        zip_path = os.path.join(
            os.environ["HOME"],
            f"{os.environ["REPO_NAME"]}-{os.environ["RELEASE_TAG"]}.zip",
        )
        print(zip_path)
        print(os.path.exists(zip_path))

      shell: python
