name: "Upload release to ShotGrid Action"
description: "Upload zipped release to ShotGrid"
runs:
  using: "composite"
  steps:
    - name: "Copy files to new folder"
      run: rsync -arv --exclude='.git/' --exclude='.github/' --exclude='.gitignore' . ./$REPO_NAME-$RELEASE_TAG
      shell: bash
    - name: "ZIP folder"
      run: zip -r $REPO_NAME-$RELEASE_TAG.zip ./$REPO_NAME-$RELEASE_TAG
      shell: bash
    - name: "Pip install Shotgun API"
      run: "python -m pip install git+https://github.com/shotgunsoftware/python-api.git@v3.3.2"
      shell: bash
    - name: "Upload to SG"
      run: |
        import os
        from shotgun_api3 import Shotgun

        # Build path to zipped 
        repo_name = os.environ["REPO_NAME"]
        release_tag = os.environ["RELEASE_TAG"]
        zip_path = f"{repo_name}-{release_tag}.zip"

        # Create ShotGrid API Instance
        sg = Shotgun(
            base_url=os.environ["SHOTGRID_URL"],
            script_name=os.environ["SHOTGRID_SCRIPT_NAME"],
            api_key=os.environ["SHOTGRID_SCRIPT_KEY"],
        )

        # Upload zipped rerelease to ShotGrid
        sg.upload(
            os.environ["SHOTGRID_ENTITY_TYPE"],
            os.environ["SHOTGRID_ENTITY_ID"],
            "release.zip",
            "sg_uploaded_app",
        )

      shell: python
