name: "Upload release to ShotGrid"
description: "Upload zipped release to ShotGrid"
runs:
  using: "composite"
  steps:
    - name: "Pip install Shotgun API"
      run: "python -m pip install git+git://github.com/shotgunsoftware/python-api.git"
      shell: bash
    - name: "ZIP Repository"
      run: |
        import os
        import shutil
        repo_path = os.environ["GITHUB_WORKSPACE"]
        repo_name = os.environ["REPO_NAME"]
        release_tag = os.environ["RELEASE_TAG"]
        output_path = os.path.join(
            os.environ["HOME"],
            f"{repo_name}-{release_tag}",
        )

        shutil.make_archive(output_path, "zip", repo_path)

      shell: python
    - name: "Upload to SG"
      run: |
        import os
        from shotgun_api3 import Shotgun

        # Build path to zipped 
        repo_name = os.environ["REPO_NAME"]
        release_tag = os.environ["RELEASE_TAG"]
        zip_path = os.path.join(
            os.environ["HOME"],
            f"{repo_name}-{release_tag}.zip",
        )

        # Create ShotGrid API Instance
        sg = Shotgun(
            base_url=os.environ["SHOTGRID_URL"],
            script_name=os.environ["SHOTGRID_SCRIPT_NAME"],
            api_key=os.environ["SHOTGRID_SCRIPT_KEY"],
        )

        # Upload zipped rerelease to ShotGrid
        sg.upload(
            os.environ["SHOTGRID_ENTITY_TYPE"],
            os.environ["SHOTGRID_ENTITY_ID"],
            zip_path,
            "sg_uploaded_app",
        )

      shell: python
